var busTime = [
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
    '09:00 PM',
    '09:40 PM',
  ],
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
  ],
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
    '09:00 PM',
    '09:40 PM',
  ],
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
    '09:00 PM',
    '09:40 PM',
  ],
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
    '09:00 PM',
    '09:40 PM',
  ],
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
    '09:00 PM',
  ],
  [
    '03:30 PM',
    '04:15 PM',
    '04:55 PM',
    '05:50 PM',
    '06:30 PM',
    '08:20 PM',
    '09:00 PM',
    '09:40 PM',
  ],
];

var busRoute = [
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
    'Institute to Sadar',
    'Sadar to Institute',
  ],
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
  ],
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
    'Institute to Sadar',
    'Sadar to Institute',
  ],
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
    'Institute to Sadar',
    'Sadar to Institute',
  ],
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
    'Institute to Sadar',
    'Sadar to Institute',
  ],
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
    'Institute to Sadar',
  ],
  [
    'Institute to Sadar',
    'Sadar to Institute',
    'Sadar to Institute',
    'Hexagon to Sadar',
    'Institute to Sadar',
    'Sadar to Institute',
    'Institute to Sadar',
    'Sadar to Institute',
  ],
];
